ADD timer.rs
arceos-hypervisor/arceos-umhv pull request #44
Opened 2024-12-12 06:56 UTC by PeizhongQiu

axdevice: https://github.com/arceos-hypervisor/axdevice/pull/5

2025-01-09 06:47 UTC, hky1999 requested changes
rebase this branch ant let's merge it!

2025-01-09 06:47 UTC, hky1999 commented on arceos-vmm/src/vmm/timer.rs
> +        thread::spawn(move || {
can we move this initialization process to `enable_virtualization` in `hal.rs`?

because this is the same percpu-core-once logic

2025-01-09 07:07 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +        thread::spawn(move || {
It doesn't feel good. In this case, TIMER_LIST would have to be set to pub, which seems beyond its scope.

2025-01-09 07:09 UTC, hky1999 commented on arceos-vmm/src/vmm/timer.rs
> +        thread::spawn(move || {
you can expose `init_percpu()` API only.

2025-01-09 08:32 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +        thread::spawn(move || {
OK

2025-01-10 06:13 UTC, hky1999 commented on arceos-vmm/src/hal.rs
> +            vmm::init_timer_percpu();
move this to line 106

2025-01-10 06:13 UTC, hky1999 commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
what is this function for

2025-01-10 06:13 UTC, hky1999 commented on arceos-vmm/src/vmm/timer.rs
> +const PERIODIC_INTERVAL_NANOS: u64 = NANOS_PER_SEC / TICKS_PER_SEC;
I do not think that we need this in our timer.

it's the duty of ArceOS

2025-01-10 06:15 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
The purpose of this function is to set the next clock expiration time

2025-01-10 06:16 UTC, hky1999 commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
who will call this function

2025-01-10 06:17 UTC, PeizhongQiu commented on arceos-vmm/src/hal.rs
> +            vmm::init_timer_percpu();
Does this make any sense?

2025-01-10 06:19 UTC, hky1999 commented on arceos-vmm/src/hal.rs
> +            vmm::init_timer_percpu();
timer should be initialized before virtualization is on.

after virtualization is enabled on each physical cpu, the irq handling routine will be changed

2025-01-10 06:27 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
Called after check_events in callback to set the next timer interrupt. Otherwise, the virtual machine may not exit for a long time.

2025-01-10 06:30 UTC, hky1999 commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
This operation will overwrite the original timer set by ArceOS.

2025-01-10 06:35 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
ArceOS timer can be used as an item in timerlist

2025-01-10 06:37 UTC, hky1999 commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
> ArceOS timer can be used as an item in timerlist

I see, enrich the comments please.

Also, please provided a DEMO with related PRs.

2025-01-10 07:09 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
When the interrupt is triggered, first need to check the event to let the expired event trigger, and then set the time for the next interrupt to trigger.
https://github.com/arceos-hypervisor/arceos-umhv/blob/66b109283fcfcdc5811cea819cd168815df333ed/arceos-vmm/src/vmm/vcpus.rs#L276-L297
When I settimer, it registers a clock interrupt.
https://github.com/arceos-hypervisor/arceos-umhv/blob/66b109283fcfcdc5811cea819cd168815df333ed/arceos-vmm/src/vmm/vcpus.rs#L326-L346

2025-01-13 03:06 UTC, luodeb commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
How should `arm` or `x86` call register_timer?

2025-01-13 03:06 UTC, luodeb commented
How should `arm` or `x86` call register_timer?

2025-01-13 04:36 UTC, PeizhongQiu commented
> How should `arm` or `x86` call register_timer?

register_timer is to register the clock interrupt in timerlist, and needs to provide the clock interrupt time and callback function. In riscv's sbi, there is a settimer, which will set the time of the next clock interrupt, and register_timer is needed here.

2025-01-14 06:06 UTC, hky1999 commented
> How should `arm` or `x86` call register_timer?

I am working in progress on x86 virtual lapic timer, I think we need a more general abstraction of timer.

2025-01-14 06:09 UTC, hky1999 commented
> > How should `arm` or `x86` call register_timer?
> 
> register_timer is to register the clock interrupt in timerlist, and needs to provide the clock interrupt time and callback function. In riscv's sbi, there is a settimer, which will set the time of the next clock interrupt, and register_timer is needed here.

If this design works well on arm and riscv, you can merge it first.
Coordinate with @luodeb  to make sure this works under aarch64.

> When the interrupt is triggered, first need to check the event to let the expired event trigger, and then set the time for the next interrupt to trigger.

enrich the comments of APIs in timers please.

like how users should use it, when users should use it.

2025-01-14 06:13 UTC, hky1999 commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
```rust
 AxVCpuExitReason::ExternalInterrupt { vector } => { 
     debug!("VM[{}] run VCpu[{}] get irq {}", vm_id, vcpu_id, vector); 
     match vector { 
         10 => { 
             // riscv timer 
             // error!("external timer handle"); 
             axtask::on_timer_tick(); 
             check_events(); 
             scheduler_next_event(); 
```

about this, should we call `axtask::on_timer_tick();` every time a timer `ExternalInterrupt` triggered?

on we just call `check_events();` and let the TimerList to judge whether we should call the `axtask::on_timer_tick();`

2025-01-14 06:24 UTC, aarkegz requested changes

2025-01-14 06:24 UTC, aarkegz commented on arceos-vmm/src/vmm/timer.rs
> +use std::os::arceos::modules::axhal;
Merge these uses?

2025-01-14 06:24 UTC, aarkegz commented on arceos-vmm/src/vmm/timer.rs
> +pub struct VmmTimerEvent {
Add some doc-comment here please.

2025-01-14 06:24 UTC, aarkegz commented on arceos-vmm/src/vmm/timer.rs
> +pub struct VmmTimerEvent {
For following functions too. I agree with @hky1999 that comments should be enriched here.

2025-01-14 06:24 UTC, aarkegz commented on arceos-vmm/src/vmm/timer.rs
> +pub fn cancel_timer<F>(condition: F)
It's not really convenient to use this function, as `VmmTimerEvent` doesn't provide any `id` field. Maybe we should add one? Or maybe `register_timer` should accept any `impl FnOnce(TimeValue) + Send + 'static` as handler and returns a `CancelToken` to be used in `cancel_timer`?

2025-01-14 06:33 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +pub fn scheduler_next_event() {
no, this is just a demo to test schedule

2025-01-14 06:34 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +pub fn cancel_timer<F>(condition: F)
do you mean something like this?
https://github.com/arceos-hypervisor/axdevice/blob/e7ec8282d2b5c0bb91f4d87afacba100df2ed94f/src/timer.rs#L52-L78

2025-01-14 08:14 UTC, aarkegz commented on arceos-vmm/src/vmm/timer.rs
> +pub fn cancel_timer<F>(condition: F)
Yes.

2025-01-14 13:11 UTC, PeizhongQiu commented on arceos-vmm/src/vmm/timer.rs
> +pub fn cancel_timer<F>(condition: F)
I push a new commit which contain token and doc.

2025-01-14 16:43 UTC, aarkegz approved these changes
LGTM now, how's your opinion? @hky1999 @luodeb

2025-01-14 17:58 UTC, hky1999 commented
> LGTM now, how's your opinion? @hky1999 @luodeb

So do I, LGTM

thanks for the hard work @PeizhongQiu

2025-01-14 17:59 UTC, hky1999 approved these changes

2025-01-14 21:58 UTC, aarkegz commented
BTW please rename the PR before merging @PeizhongQiu .

2025-01-15 03:53 UTC, merged